"""
ComfyUI-DetailGen3D Nodes
"""

from .load_model import LoadDetailGen3DModel, NODE_CLASS_MAPPINGS as LOAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY
from .prepare_mesh import DetailGen3D_PrepareMesh, NODE_CLASS_MAPPINGS as PREPARE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PREPARE_DISPLAY
from .generate import DetailGen3D_Generate, NODE_CLASS_MAPPINGS as GENERATE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GENERATE_DISPLAY

# Collect all node class mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PREPARE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GENERATE_MAPPINGS)

# Collect all display name mappings
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PREPARE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(GENERATE_DISPLAY)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
